import { StyleSheet } from "react-native";

const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 100,
    alignItems: "center",
    backgroundColor: "#fff",
  },
  title: {
    fontFamily: "Jersey10-Regular",
    textAlign: 'center',
    fontSize: 70,
    marginTop: 200,
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 30,
    marginBottom: 30,
    color: "#666",
    fontFamily: "VT323-Regular",
    textAlign: 'center',
  },
  button: {
    width: "80%",
    backgroundColor: "#333",
    paddingVertical: 15,
    borderRadius: 10,
    marginVertical: 10,
    alignItems: "center",
  },
  buttonText: {
    color: "#fff",
    fontSize: 18,
    fontFamily: "VT323-Regular",
  },
  inputBox: {
    width: '80%',
    backgroundColor: '#222',
    borderRadius: 12,
    padding: 20,
    marginVertical: 20,
    borderWidth: 2,
    borderColor: '#444',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  label: {
    color: '#fff',
    fontFamily: 'VT323-Regular',
    fontSize: 28,
    marginBottom: 15,
    textAlign: 'center',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  input: {
    height: 60,
    width: '70%',
    backgroundColor: '#111',
    borderWidth: 2,
    borderColor: '#333',
    borderRadius: 8,
    paddingHorizontal: 15,
    color: '#fff',
    fontFamily: 'VT323-Regular',
    fontSize: 32,
    textAlign: 'center',
  },
  invalidInput: {
    borderColor: '#ff4444',
    backgroundColor: '#330000',
  },
  unitDisplay: {
    width: '25%',
    height: 60,
    backgroundColor: '#333',
    borderWidth: 2,
    borderColor: '#444',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  unitText: {
    color: '#fff',
    fontFamily: 'Jersey10-Regular',
    fontSize: 32,
  },
  noteText: {
    color: '#aaa',
    fontFamily: 'VT323-Regular',
    fontSize: 20,
    marginTop: 15,
    textAlign: 'center',
    fontStyle: 'italic',
  },
});

export default globalStyles;